# Top level comment
root /var/www/html;
# another comment
index index.html;

server {
    # server-level comment
    listen 8080;
    server_name localhost;
    root /var/www/html;

    location / {
        limit_except GET;
    }
}
