server {
    listen 8080;
    server_name example.com www.example.com;
    root /var/www/example;
    index index.html;
    error_page 404 /404.html;

    location / {
        limit_except GET;
        autoindex off;
    }

    location /api {
        limit_except GET POST DELETE;
        autoindex off;
    }
}

server {
    listen 8081;
    server_name test.com;
    root /var/www/test;
    index index.html;

    location / {
        limit_except GET POST;
        autoindex on;
    }
}
