server {
    listen 18080;
    listen 127.0.0.1:18081;
    server_name localhost default_server;
    root /www;
    index index.html;
    autoindex off;
    client_max_body_size 20000000;
    error_page 404 /error/404.html;
    cgi_handler .py /opt/homebrew/bin/python3;

    location / {
        limit_except GET;
        autoindex off;
    }

    location /uploads {
        limit_except GET POST;
        upload_path /www/uploads;
        autoindex on;
    }

    location /tiny-post {
        limit_except POST;
        upload_path /www/uploads;
        client_max_body_size 20;
        autoindex off;
    }

    location /geneva_birds {
        limit_except GET POST;
        root /www;
        index index.html;
        autoindex off;
    }

    location /geneva_birds/cgi {
        limit_except GET POST;
        root /www;
        cgi_handler .py /opt/homebrew/bin/python3;
        autoindex off;
    }

    location /geneva_birds/uploads {
        limit_except GET DELETE;
        root /www;
        autoindex on;
    }

    location /cgi {
        limit_except GET POST;
        root /www;
        cgi_handler .py /opt/homebrew/bin/python3;
        autoindex off;
    }

    location /redirect {
        return 301 /geneva_birds/;
    }
}

server {
    listen 127.0.0.1:18082;
    server_name birds.local;
    root /www/geneva_birds;
    index index.html;
    autoindex off;
    error_page 404 /error/404.html;

    location / {
        limit_except GET;
        root /www/geneva_birds;
        index index.html;
        autoindex off;
    }

    location /cgi {
        limit_except GET POST;
        root /www/geneva_birds;
        cgi_handler .py /opt/homebrew/bin/python3;
        autoindex off;
    }

    location /uploads {
        limit_except GET POST;
        root /www/geneva_birds;
        upload_path /www/geneva_birds/uploads;
        autoindex on;
    }
}
