server {
    listen 8080;
    server_name localhost;
    root /var/www/html;
    cgi_handler .php /usr/bin/php;
    cgi_handler .py /usr/bin/python3;

    location / {
        limit_except GET;
    }
}
