/* ========================================================================== */
/* ARCHITECTURAL DIFFERENCES                                                  */
/* ========================================================================== */

//* 1. Address Translation
//+    - Your Code: Manually uses inet_pton() to translate a hardcoded string 
//+      ("127.0.0.1") into binary.
//+    - Her Code: Uses getaddrinfo(), which automatically resolves hostnames 
//+      (like "localhost" or "example.com") into IPs.
//
//* 2. Protocol Flexibility
//+    - Your Code: Hardcoded AF_INET, meaning your server will ONLY ever 
//+      work with IPv4.
//+    - Her Code: Passed AF_UNSPEC to hints, meaning the server dynamically 
//+      handles IPv4 or IPv6 depending on what the OS provides.
//
//* 3. Memory Allocation
//+    - Your Code: Strictly uses stack allocation (struct sockaddr_in). 
//+      No memory leaks possible.
//+    - Her Code: Uses dynamically allocated linked lists generated by 
//+      getaddrinfo() (which MUST be freed using freeaddrinfo() to avoid leaks).
//
//* 4. Server Lifespan
//+    - Your Code: Uses a while(1) loop, keeping the server alive to handle 
//+      infinite sequential requests.
//+    - Her Code: Has no loop, so the program exits immediately after 
//+      sending a single webpage.
//
//* 5. Safety & Stability
//+    - Your Code: Meticulously checks the return values of socket(), bind(), 
//+      and listen() to prevent silent failures.
//+    - Her Code: Skips error checking entirely. If port 8080 is already 
//+      in use, her program crashes blindly.


#include <iostream>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <stdio.h>
#include <string.h>
#include <arpa/inet.h>
#include <netinet/in.h>

int main()
{
    int status;
    
    // + 'hints' is the struct where we define our "wishlist" for the connection.
    // + We fill this out to tell the OS exactly what kind of sockets we are looking for.
    struct addrinfo hints;
    
    // + 'servinfo' is just an uninitialized pointer right now. 
    // + We DO NOT malloc it. The 'getaddrinfo' function will allocate memory 
    // + for a linked list of results and make this pointer point to the head of it.
    struct addrinfo *servinfo; 
    
    // + This struct is large enough to hold either an IPv4 or IPv6 address.
    // + It will store the actual IP address of the browser that connects to us later.
    struct sockaddr_storage their_addr;
    socklen_t addr_size;
    
    int sockfd;
    int new_fd;
    char buf[1];
    int byte_count;

    // + Always clear the struct before using it to avoid garbage values.
    memset(&hints, 0, sizeof hints); 
    
    // + AF_UNSPEC means "I am agnostic. Give me either IPv4 or IPv6."
    hints.ai_family = AF_UNSPEC; 
    
    // + SOCK_STREAM means we want a reliable, two-way connection (TCP, not UDP).
    hints.ai_socktype = SOCK_STREAM; 
    
    // + AI_PASSIVE tells the OS: "Automatically fill in my local machine's IP for me."
    // + This is why we pass NULL as the first argument to getaddrinfo later.
    hints.ai_flags = AI_PASSIVE; 

    std::cout << std::endl << "hints" << std::endl;
    std::cout << hints.ai_family << std::endl;
    std::cout << hints.ai_socktype<< std::endl;
    std::cout << hints.ai_flags << std::endl;

    std::cout << std::endl << "servinfo" << std::endl;

    // + DANGER: SEGMENTATION FAULT HERE!
    // + At this exact moment, 'servinfo' is an uninitialized pointer. 
    // + getaddrinfo() hasn't been called yet, so it points to random memory.
    // + Trying to print servinfo->ai_flags tries to read memory we don't own.
    // std::cout << servinfo->ai_flags << std::endl;
    // std::cout << servinfo->ai_family << std::endl;
    // std::cout << servinfo->ai_socktype << std::endl;
    // std::cout << servinfo->ai_protocol << std::endl;
    // std::cout << servinfo->ai_addrlen << std::endl;

    // + This is the magic function of Beej's Guide.
    // + 1. NULL: We want our own IP (because of AI_PASSIVE).
    // + 2. "8080": The port we want to use.
    // + 3. &hints: Our wishlist.
    // + 4. &servinfo: The pointer where the OS will attach the results.
    // + If successful, 'servinfo' now points to valid, allocated memory containing
    // + fully prepped structs ready to be used by socket() and bind().
    status = getaddrinfo(NULL, "8080", &hints, &servinfo);

    // + Now that getaddrinfo has run, these prints would actually work!
    std::cout << servinfo->ai_flags << std::endl;
    std::cout << servinfo->ai_family << std::endl;
    std::cout << servinfo->ai_socktype << std::endl;
    std::cout << servinfo->ai_protocol << std::endl;
    std::cout << servinfo->ai_addrlen << std::endl;

    // + Instead of hardcoding AF_INET and SOCK_STREAM like you did, 
    // + she just passes the values dynamically generated by getaddrinfo.
    sockfd = socket(servinfo->ai_family, servinfo->ai_socktype, servinfo->ai_protocol);
    
    // + Same here. She binds the socket using the pre-filled address struct.
    bind(sockfd, servinfo->ai_addr, servinfo->ai_addrlen);
    
    // + Tells the OS to queue up to 10 incoming connections.
    listen(sockfd, 10);

    addr_size = sizeof their_addr;
    
    // + The server halts here and waits. 
    // + When a browser connects, accept() returns a brand new file descriptor (new_fd).
    // + The original 'sockfd' is left alone to continue listening for other people.
    new_fd = accept(sockfd, (struct sockaddr *)&their_addr, &addr_size);

    //byte_count = recv(new_fd, buf, sizeof buf, 0);
    //printf("recv()'d %d bytes of data in buf\n", byte_count);

    // + She hardcodes a valid HTTP response.
    // + \r\n\r\n is the mandatory empty line separating HTTP headers from the body.
    const char *response = "HTTP/1.1 200 OK\r\nContent-Length: 56\r\n\r\n<html><body><h1>Hello!</h1><p>Mon serveur marche</p></body></html>";
    
    // + Sends the response back to the browser via the specific connection fd.
    send(new_fd, response, strlen(response), 0);

    // + Note: She forgot to call close(new_fd) and close(sockfd).
    // + She also forgot to free the memory allocated by getaddrinfo using freeaddrinfo(servinfo).
}

//----------------------------------------------------------------------------------------

#include <iostream>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <netdb.h>
#include <cstring>

int main(void)
{
    // + sockaddr_in is the specific structure used for IPv4 addresses.
    struct sockaddr_in myaddr;

    // + We clear the structure to 0 to avoid garbage data causing bind() to fail.
    std::memset(&myaddr, 0, sizeof(myaddr));
    
    // + We manually specify that we are using the IPv4 protocol family.
    myaddr.sin_family = AF_INET;
    
    // + htons() converts the port from Host byte order to Network byte order.
    // + (Computers read memory differently, this standardizes it for the network).
    myaddr.sin_port = htons(8080);

    // + inet_pton converts the human-readable string "127.0.0.1" into binary format.
    // + This rigidly locks your server to this exact local loopback IP address.
    int retInet = inet_pton(AF_INET, "127.0.0.1", &(myaddr.sin_addr));
    if (retInet == -1) 
    { 
        std::cout << "inet error" << std::endl; 
        return (-1); 
    }
    if (retInet == 0)  
    { 
        std::cout << "invalid address" << std::endl; 
        return (-1); 
    }

    // + We manually ask the OS for an IPv4 (PF_INET), TCP (SOCK_STREAM) socket.
    int socketfd = socket(PF_INET, SOCK_STREAM, 0);
    if (socketfd == -1) 
    { 
        std::cout << "socket error" << std::endl; 
        return (-1); 
    }

    // + setsockopt with SO_REUSEADDR prevents the "Address already in use" error 
    // + if you kill your server and immediately restart it. This is excellent practice.
    int opt = 1;
    if (setsockopt(socketfd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt)) == -1) 
    {
        std::cout << "setsockopt error" << std::endl;
        return (-1);
    }

    // + bind() assigns the IP and Port we manually configured in 'myaddr' to 'socketfd'.
    if (bind(socketfd, (struct sockaddr*)&myaddr, sizeof(myaddr)) == -1)
    { 
        std::cout << "bind error" << std::endl; 
        return (-1); 
    }

    // + listen() tells the OS to start accepting incoming connections. 
    // + The 10 is the backlog: how many incoming connections can wait in line at once.
    if (listen(socketfd, 10) == -1)
    { 
        std::cout << "listen error" << std::endl; 
        return (-1); 
    }

    // + This structure will hold the IP address of whatever browser connects to us.
    struct sockaddr_in their_addr;
    std::memset(&their_addr, 0, sizeof(their_addr));
    socklen_t addr_size = sizeof(their_addr);

    // + The infinite loop keeps the server alive to handle request after request.
    while (1)
    {
        // + accept() blocks (pauses execution) until someone actually connects.
        // + It creates a NEW file descriptor (newfd) for this specific client conversation.
        int newfd = accept(socketfd, (struct sockaddr *)&their_addr, &addr_size);
        if (newfd == -1)
        {
            continue;
        }

        // + We read up to 4095 bytes of what the browser sent us (the HTTP Request).
        char buf[4096];
        int bytes = recv(newfd, buf, sizeof(buf) - 1, 0);
        if (bytes != -1)
        {
            // + We null-terminate the buffer so we can print it safely as a C-string.
            buf[bytes] = '\0';
            std::cout << buf << std::endl;
        }

        // + We construct a minimal but valid HTTP response header + body.
        std::string response = "HTTP/1.1 200 OK\r\nContent-Length: 11\r\n\r\nHello World";
        
        // + We push the response back through the newly created client file descriptor.
        send(newfd, response.c_str(), response.size(), 0);

        // + We close the specific client connection, but socketfd stays open for the next person!
        close(newfd);
    }
}
